M48
; DRILL file {KiCad 6.0.5+dfsg-1} date Sun 12 Jun 2022 07:50:49 PM CST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-12T19:50:49+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0472
%
G90
G05
T1
X6.122Y-1.6575
X6.2795Y-1.6575
T2
X7.2441Y-1.5805
X7.3622Y-1.5805
T3
X7.2913Y-1.9803
T0
M30
